'use strict';
/**
 * Status codes and their UI criticality (UI.CriticalityType) used by the mock backend.
 * The code lists are part of the project contract (code list entity sets *VH in ZUI_STC_TEST_CASE_O4).
 */

const CRITICALITY = Object.freeze({ NEUTRAL: 0, NEGATIVE: 1, CRITICAL: 2, POSITIVE: 3, INFORMATION: 5 });

const VALIDATION = Object.freeze({ NOT_VALIDATED: 'NOT_VALIDATED', VALID: 'VALID', AMBIGUOUS: 'AMBIGUOUS', INVALID: 'INVALID' });
const APPROVAL = Object.freeze({ NOT_APPROVED: 'NOT_APPROVED', APPROVED: 'APPROVED', REVOKED: 'REVOKED' });
const EXECUTION = Object.freeze({ NOT_STARTED: 'NOT_STARTED', RUNNING: 'RUNNING', FINISHED: 'FINISHED', FAILED: 'FAILED', CANCELLED: 'CANCELLED' });
const RESULT = Object.freeze({
    NONE: '',
    PASSED: 'PASSED',
    PASSED_WITH_WARNING: 'PASSED_WITH_WARNING',
    FAILED_FUNCTIONAL: 'FAILED_FUNCTIONAL',
    FAILED_TECHNICAL: 'FAILED_TECHNICAL',
    BLOCKED: 'BLOCKED'
});
const LIFECYCLE = Object.freeze({
    CAPTURED: 'CAPTURED',
    VALIDATED: 'VALIDATED',
    APPROVED: 'APPROVED',
    IN_EXECUTION: 'IN_EXECUTION',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
});
const ITEM_STATUS = Object.freeze({ SUCCESS: 'SUCCESS', WARNING: 'WARNING', ERROR: 'ERROR', INFO: 'INFO' });
const STEP_STATUS = Object.freeze({ PLANNED: 'PLANNED', RUNNING: 'RUNNING', DONE: 'DONE', FAILED: 'FAILED', SKIPPED: 'SKIPPED' });
const ASSERTION = Object.freeze({ PASSED: 'PASSED', WARNING: 'WARNING', FAILED: 'FAILED', NOT_EVALUATED: 'NOT_EVALUATED' });

const BO = Object.freeze({
    TEST_CASE: 'TEST_CASE',
    SERVICE_REQUEST: 'SERVICE_REQUEST',
    SERVICE_QUOTATION: 'SERVICE_QUOTATION',
    SERVICE_ORDER: 'SERVICE_ORDER',
    SERVICE_CONFIRMATION: 'SERVICE_CONFIRMATION',
    BILLING_DOC_REQUEST: 'BILLING_DOC_REQUEST',
    BILLING_DOCUMENT: 'BILLING_DOCUMENT'
});

const BO_LABEL = Object.freeze({
    TEST_CASE: 'Test Case',
    SERVICE_REQUEST: 'Service Request',
    SERVICE_QUOTATION: 'Service Quotation',
    SERVICE_ORDER: 'Service Order',
    SERVICE_CONFIRMATION: 'Service Confirmation',
    BILLING_DOC_REQUEST: 'Billing Document Request',
    BILLING_DOCUMENT: 'Billing Document'
});

const CRITICALITY_BY_CODE = {
    // positive
    VALID: CRITICALITY.POSITIVE,
    APPROVED: CRITICALITY.POSITIVE,
    FINISHED: CRITICALITY.POSITIVE,
    PASSED: CRITICALITY.POSITIVE,
    SUCCESS: CRITICALITY.POSITIVE,
    DONE: CRITICALITY.POSITIVE,
    COMPLETED: CRITICALITY.POSITIVE,
    VALIDATED: CRITICALITY.POSITIVE,
    // critical
    AMBIGUOUS: CRITICALITY.CRITICAL,
    PASSED_WITH_WARNING: CRITICALITY.CRITICAL,
    WARNING: CRITICALITY.CRITICAL,
    // negative
    INVALID: CRITICALITY.NEGATIVE,
    FAILED: CRITICALITY.NEGATIVE,
    FAILED_FUNCTIONAL: CRITICALITY.NEGATIVE,
    FAILED_TECHNICAL: CRITICALITY.NEGATIVE,
    ERROR: CRITICALITY.NEGATIVE,
    BLOCKED: CRITICALITY.NEGATIVE,
    CANCELLED: CRITICALITY.NEGATIVE,
    REVOKED: CRITICALITY.NEGATIVE,
    // information
    RUNNING: CRITICALITY.INFORMATION,
    IN_EXECUTION: CRITICALITY.INFORMATION,
    INFO: CRITICALITY.INFORMATION
};

/**
 * @param {string} code status code
 * @returns {number} UI.CriticalityType value
 */
function criticalityOf(code) {
    return CRITICALITY_BY_CODE[code] ?? CRITICALITY.NEUTRAL;
}

module.exports = {
    CRITICALITY,
    VALIDATION,
    APPROVAL,
    EXECUTION,
    RESULT,
    LIFECYCLE,
    ITEM_STATUS,
    STEP_STATUS,
    ASSERTION,
    BO,
    BO_LABEL,
    criticalityOf
};
